apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  client-java-options: -Xms1024m -Xmx1024m
  client-node-replicas: 1
  data-java-options: -Xms2048m -Xmx2048m
  data-node-replicas: 1
  data-volume-size: 10Gi
  elastic-search-image: quay.io/pires/docker-elasticsearch-kubernetes:6.4.2
  master-java-options: -Xms2048m -Xmx2048m
  master-node-replicas: 1
  network-host: 0.0.0.0
  resources:
    requests:
      memory: 1024Mi
      cpu: 200m
    limits:
      memory: 2048Mi
      cpu: 1
  snapshot:
    bucketName: elasticsnapshots
    enabled: false
    schedule: '@every 2m'
  storage:
    classProvisioner: volume.alpha.kubernetes.io/storage-class
    reclaimPolicy: Delete
    type: gp2
  use-ssl: false
  zone: []
