apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-storage
  namespace: logging
provisioner: kubernetes.io/host-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath-storage
  resources:
    requests:
      storage: 30Gi
