apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: logging
  labels:
    app: kibana
data:
  kibana.yml: |-
    elasticsearch.url: http://elasticsearch:9200
    server.host: "0"
    server.name: kibana
