apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  # 从umpc-enterprises仓库找到的一段配置,它将elasticsearch,kibana,cerebro集中在了一起
  # 但我希望各自独立
  #kibana:
  #  image: docker.elastic.co/kibana/kibana-oss:6.1.3
  #cerebro:
  #  image: upmcenterprises/cerebro:0.6.8
  #elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_1
  elastic-search-image: quay.io/pires/docker-elasticsearch-kubernetes:6.4.2
  client-node-replicas: 1
  master-node-replicas: 1
  data-node-replicas: 3
  client-java-options: -Xms1024m -Xmx1024m
  master-java-options: -Xms2048m -Xmx2048m
  data-java-options: -Xms2048m -Xmx2048m
  data-volume-size: 10Gi
  network-host: 0.0.0.0
  resources:
    requests:
      memory: 1024Mi
      cpu: 200m
    limits:
      memory: 2048Mi
      cpu: 1
  #snapshot:
    #bucketName: elasticsnapshots
    #enabled: false
    #schedule: '@every 2m'
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
    image: upmcenterprises/elasticsearch-cron:0.0.4
  storage:
    #classProvisioner: volume.alpha.kubernetes.io/storage-class
    #reclaimPolicy: Delete
    #type: gp2
    storage-class: hostpath-storage
  use-ssl: false
  zone: []
