apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: fluent-bit
  namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  # pod的更新策略为滚动更新,如pod滚动更新时最多允许减少25%,最多允许增加25%
  updateStrategy:
    type: RollingUpdate
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      # 是否使用主机网络,默认为false;如果为true,则表示容器使用宿主机网络,不再使用docker网桥,pod无法再同一宿主机有2个副本
      hostNetwork: false
      # 设置pod的DNS策略,默认为ClusterFirst;有效值有ClusterFirstWithHostNet,ClusterFirst,Default(None)
      dnsPolicy: ClusterFirst
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.0.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2020
        readinessProbe:
          httpGet:
            path: /api/v1/metrics/prometheus
            port: 2020
        livenessProbe
          httpGet:
            path: /
            port: 2020
        env:
        - name: KAFKA_HOST
          value: "rest.kafka.svc.cluster.local"
        - name: KAFKA_PORT
          value: "80"
        - name: KAFKA_TOPIC
          value: fluent-bit
        resources:
          requests:
            memory: 10Mi
            cpu: 5m
          limits:
            memory: 60Mi
            cpu: 50m
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-service.conf
          subPath: fluent-bit-service.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-input.conf
          subPath: fluent-bit-input.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-filter.conf
          subPath: fluent-bit-filter.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-output.conf
          subPath: fluent-bit-output.conf
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluent-bit-config
      # pod终止时的宽限期;0表示立即删除pod,或者可以设置一个宽限时间
      terminationGracePeriodSeconds: 10
