#!/bin/bash

set -e

HOST=`hostname -s`
DOMAIN=`hostname -d`
BROKER_ID=${HOST##*-}

NUM_NETWORK_THREADS=${NUM_NETWORK_THREADS:-3}
NUM_IO_THREADS=${NUM_IO_THREADS:-3}
SOCKET_SEND_BUFFER_BYTES=${SOCKET_SEND_BUFFER_BYTES:-102400}
SOCKET_RECEIVE_BUFFER_BYTES=${SOCKET_RECEIVE_BUFFER_BYTES:-102400}
SOCKET_REQUEST_MAX_BYTES=${SOCKET_REQUEST_MAX_BYTES:-104857600}
LOG_DIRS=${LOG_DIRS:-/tmp/kafka-logs}
NUM_PARTITIONS=${NUM_PARTITIONS:-1}
NUM_RECOVERY_THREADS_PER_DATA_DIR=${NUM_RECOVERY_THREADS_PER_DATA_DIR:-1}
OFFSETS_TOPIC_REPLICATION.FACTOR=${OFFSETS_TOPIC_REPLICATION_FACTOR:-1}
TRANSACTION_STATE_LOG_MIN_ISR=${TRANSACTION_STATE_LOG_MIN_ISR:-1}
#LOG_FLUSH_INTERVAL_MESSAGES=${LOG_FLUSH_INTERVAL_MESSAGES:-10000}
#LOG_FLUSH_INTERVAL_MS=${LOG_FLUSH_INTERVAL_MS:-1000}
LOG_RETENTION_HOURS=${LOG_RETENTION_HOURS:-168}
#LOG_RETENTION_BYTES=${LOG_RETENTION_BYTES:-1073741824}
LOG_SEGMENT_BYTES=${LOG_SEGMENT_BYTES:-1073741824}
LOG_RETENTION_CHECK_INTERVAL_MS=${LOG_RETENTION_CHECK_INTERVAL_MS:-300000}
ZOOKEEPER_CONNECT=${ZOOKEEPER_CONNECT:-localhost:2181}
ZOOKEEPER_CONNECTION_TIMEOUT_MS=${ZOOKEEPER_CONNECTION_TIMEOUT_MS:-6000}
GROUP_INTERVAL_REBALANCE_DELAY_MS=${GROUP_INTERVAL_REBALANCE_DELAY_MS:-0}


KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
KAFKA_ZOOKEEPER_CONNECT="zookeeper:2181"
KAFKA_LOG_DIRS="/opt/kafka/data/logs"
KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE="false"
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="3"
KAFKA_JMX_PORT="5555"

CONF_DIR=/opt/kafka/config

function create_server_properties() {
	mv $CONF_DIR/server.properties{,.bak}
	broker.id=$BROKER_ID
	#listeners=PLAINTEST://:9002
	#advertised.listeners=PLAINTEXT://your.host.name:9092
	#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
	num.network.threads=3
	num.io.threads=3
	socket.send.buffer.bytes=102400
	socket.receive.buffer.bytes=102400
	socket.request.max.bytes=104857600
	log.dirs=/tmp/kafka-logs
	num.partitions=1
	num.recovery.threads.per.data.dir=1
	offsets.topic.replication.factor=1
	transaction.state.log.min.isr=1
	#log.flush.interval.messages=10000
	#log.flush.interval.ms=1000
	log.retention.hours=168
	#log.retention.bytes=1073741824
	log.segment.bytes=1073741824
	log.retention.check.interval.ms=300000
	zookeeper.connect=localhost:2181
	zookeeper.connection.timeout.ms=6000
	group.interval.rebalance.delay.ms=0

}

exec "$@"
